#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

MODIFIED_FILES=`git diff-index --name-status $against -- | grep -E '^[AUM].*\.rb$'| cut -c3-`

if [ -n "${MODIFIED_FILES}" ]; then
  bundle exec rubocop -a ${MODIFIED_FILES}
fi
