#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

for FILE in `git diff-index --name-status $against -- | grep -E '^[AUM].*\.rb$'| cut -c3-`; do
  MODIFIED_FILES="${MODIFIED_FILES} ${FILE}"
done

bundle exec rubocop ${MODIFIED_FILES}